{
 "title": "I-Joy",
 "time": { "from": "now-9d", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Заряд",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  battery_percentage\nFROM sensors_data\nWHERE\n  $__timeFilter(\"time\")\nORDER BY 1"
    }
   ]
  },
  {
   "title": "12vBat",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  v12_battery_voltage\nFROM sensors_data\nWHERE\n  $__timeFilter(\"time\")\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Заряд",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  battery_percentage\nFROM sensors_data\nWHERE\n  $__timeFilter(\"time\")\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Температура в салоне",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  in_board_temp\nFROM sensors_data\nWHERE\n  $__timeFilter(\"time\")\nORDER BY 1"
    }
   ]
  },
  {
   "title": "12vBat",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  v12_battery_voltage\nFROM sensors_data\nWHERE\n  $__timeFilter(\"time\")\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Температура батареи",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  battery_temp\nFROM sensors_data\nWHERE\n  $__timeFilter(\"time\")\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Климат",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  outside_temp,\n  in_board_temp,\n  climate_target_temp\nFROM sensors_data\nWHERE\n  $__timeFilter(\"time\")\nORDER BY 1"
    }
   ]
  },
  {
   "title": "BatTemp",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 9, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  battery_temp,\n  coolant_temp,\n  outside_temp\nFROM sensors_data\nWHERE\n  $__timeFilter(\"time\")\nORDER BY 1"
    }
   ]
  }
 ]
}